arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]
#  - tegra         # [aarch64]
c_stdlib_version:  # [linux]
  - 2.28           # [linux and aarch64]
  - 2.28           # [linux and x86_64]
