github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_64: linux_64
  linux_aarch64: linux_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_64: default
  linux_aarch64: default
